# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61a4d9c4fb08d055551435418b6c218543287f7d8598c923cf32d9578d9d44887173dccb53aa4583e839f79120faf68ca4a3928c8ec8f76860eb79118f8157a2
  secret_token: mQWgouussWUWDrt6ym50zwvqF4RufzqNLxfDvO7Uo3aYBH5Uy1Pza0OoOmz8tVaOhmZPB3CHNF6okogpAalyLyuEkoS9PB5tZW2xAt1pIgvXp1iv02Ae5pOcjvcxQ3GfAn
  paypal_host: https://www.sandbox.paypal.com
  app_host: https://2258c3ea.ngrok.com
  wordpress_payment_url: http://speedlancer.com/form/ipn

production:
  secret_key_base: 2hoSUGw3CzlB2uqequxAmMsxIsMEGRpjp2kDTlcpqXLmHT5U79KTEsePYiEv2hmqOluMLvULHoTb1UebrDLeKUXJtjmG3xVM2QO0rcbMfjfbYFAN860WQWtrisADFRiHc7
  secret_token: S1c2TDMQ8igxqo5SL3hyGRXUCJIGjoWOErma5k5jaZxkiJ0ZbaN9g2rMFKE02H2tUND22HEM6GbQIRNh2XT7GjKaQPUqGyqRs4tHv3qMRSL4iQifeDsokZUpYrOXODbDIo
  paypal_host: https://www.paypal.com
  app_host: http://app.speedlancer.com/
  wordpress_payment_url: http://speedlancer.com/form/ipn
